name: .NET API CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore using solution file
    - name: Restore dependencies
      run: dotnet restore ./ProductCatalogApi.sln

    # Build solution
    - name: Build solution
      run: dotnet build ./ProductCatalogApi.sln --configuration Release --no-restore

    # Run tests (safe even if you have none)
    - name: Run tests
      run: dotnet test ./ProductCatalogApi.sln --configuration Release --no-build --verbosity normal

    # Publish API project
    - name: Publish API
      run: dotnet publish ./ProductCatalogApi/ProductCatalogApi.csproj -c Release -o ./publish

    # Upload published artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: product-catalog-api
        path: publish
